# Breast Cancer Classifier using various Supervised Machine Learning Algorithms
### SP901 Peer-Graded Assignment #2

## Data Preparation

### Import necessary libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Import Breast Cancer dataset

In [1]:
from sklearn.datasets import load_breast_cancer

### Create and instance of the breast cancer dataset

In [3]:
df=load_breast_cancer()

In [7]:
print(df.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

### Check the features of the dataset

In [4]:
df['feature_names']

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

### Create a dataframe containing the Tumor Data

In [5]:
df_features=pd.DataFrame(data=df['data'],columns=df['feature_names'])

### Display the first five items of the dataset

In [6]:
df_features.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

### Check statistical description of numeric features

In [7]:
df_features.describe().transpose()

count        mean         std         min  \
mean radius              569.0   14.127292    3.524049    6.981000   
mean texture             569.0   19.289649    4.301036    9.710000   
mean perimeter           569.0   91.969033   24.298981   43.790000   
mean area                569.0  654.889104  351.914129  143.500000   
mean smoothness          569.0    0.096360    0.014064    0.052630   
mean compactness         569.0    0.104341    0.052813    0.019380   
mean concavity           569.0    0.088799    0.079720    0.000000   
mean concave points      569.0    0.048919    0.038803    0.000000   
mean symmetry            569.0    0.181162    0.027414    0.106000   
mean fractal dimension   569.0    0.062798    0.007060    0.049960   
radius error             569.0    0.405172    0.277313    0.111500   
texture error            569.0    1.216853    0.551648    0.360200   
perimeter error          569.0    2.866059    2.021855    0.757000   
area error               569.0   40.337079   45.491006    6.802000   
smoothness error         569.0    0.007041    0.003003    0.001713   
compactness error        569.0    0.025478    0.017908    0.002252   
concavity error          569.0    0.031894    0.030186    0.000000   
concave points error     569.0    0.011796    0.006170    0.000000   
symmetry error           569.0    0.020542    0.008266    0.007882   
fractal dimension error  569.0    0.003795    0.002646    0.000895   
worst radius             569.0   16.269190    4.833242    7.930000   
worst texture            569.0   25.677223    6.146258   12.020000   
worst perimeter          569.0  107.261213   33.602542   50.410000   
worst area               569.0  880.583128  569.356993  185.200000   
worst smoothness         569.0    0.132369    0.022832    0.071170   
worst compactness        569.0    0.254265    0.157336    0.027290   
worst concavity          569.0    0.272188    0.208624    0.000000   
worst concave points     569.0    0.114606    0.065732    0.000000   
worst symmetry           569.0    0.290076    0.061867    0.156500   
worst fractal dimension  569.0    0.083946    0.018061    0.055040   

                                25%         50%          75%         max  
mean radius               11.700000   13.370000    15.780000    28.11000  
mean texture              16.170000   18.840000    21.800000    39.28000  
mean perimeter            75.170000   86.240000   104.100000   188.50000  
mean area                420.300000  551.100000   782.700000  2501.00000  
mean smoothness            0.086370    0.095870     0.105300     0.16340  
mean compactness           0.064920    0.092630     0.130400     0.34540  
mean concavity             0.029560    0.061540     0.130700     0.42680  
mean concave points        0.020310    0.033500     0.074000     0.20120  
mean symmetry              0.161900    0.179200     0.195700     0.30400  
mean fractal dimension     0.057700    0.061540     0.066120     0.09744  
radius error               0.232400    0.324200     0.478900     2.87300  
texture error              0.833900    1.108000     1.474000     4.88500  
perimeter error            1.606000    2.287000     3.357000    21.98000  
area error                17.850000   24.530000    45.190000   542.20000  
smoothness error           0.005169    0.006380     0.008146     0.03113  
compactness error          0.013080    0.020450     0.032450     0.13540  
concavity error            0.015090    0.025890     0.042050     0.39600  
concave points error       0.007638    0.010930     0.014710     0.05279  
symmetry error             0.015160    0.018730     0.023480     0.07895  
fractal dimension error    0.002248    0.003187     0.004558     0.02984  
worst radius              13.010000   14.970000    18.790000    36.04000  
worst texture             21.080000   25.410000    29.720000    49.54000  
worst perimeter           84.110000   97.660000   125.400000   251.20000  
worst area               515.300000  686.500000  1084.

### Create a dataframe containing the dataset labels

In [8]:
df_target=pd.DataFrame(data=df.target)
df_target.head()

0
0  0
1  0
2  0
3  0
4  0

### Split the dataset into training and testing subsets

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(df_features, df_target, test_size=0.2)

# Machine Learning Model Creation

## Logistic Regression

#### Import and create an instance of the Logistic regression algorithm

In [12]:
from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression()

#### Fit the training data to train the logistic regression model

In [13]:
logreg.fit(X_train,y_train)

c:\users\service unit\appdata\local\programs\python\python38\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
c:\users\service unit\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

#### Fit the test data to the trained model to create a prediction dataset and assign to variable

In [14]:
y_pred=logreg.predict(X_test)

#### Import the Confusion matrix and Classification report metrics

In [15]:
from sklearn.metrics import confusion_matrix, classification_report

#### Compare the predicted set to the true values in the test dataset using the imported metrics

In [16]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test, y_pred))

[[41  6]
 [ 0 67]]
              precision    recall  f1-score   support

           0       1.00      0.87      0.93        47
           1       0.92      1.00      0.96        67

    accuracy                           0.95       114
   macro avg       0.96      0.94      0.94       114
weighted avg       0.95      0.95      0.95       114



## Support Vector Machine

#### Import the Support Vector Machine algorithm

In [17]:
from sklearn.svm import SVC

#### Create an instance of the SVC algorithm and train with the training dataset

In [18]:
supvec=SVC()
supvec.fit(X_train,y_train)

c:\users\service unit\appdata\local\programs\python\python38\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC()


#### Fit the test data to the trained model to create a prediction dataset and assign to variable

In [19]:
supvec_pred = supvec.predict(X_test)

#### Compare the predicted set to the true values in the test dataset using the imported metrics

In [20]:
print(confusion_matrix(y_test, supvec_pred))
print(classification_report(y_test, supvec_pred))

[[36 11]
 [ 1 66]]
              precision    recall  f1-score   support

           0       0.97      0.77      0.86        47
           1       0.86      0.99      0.92        67

    accuracy                           0.89       114
   macro avg       0.92      0.88      0.89       114
weighted avg       0.90      0.89      0.89       114



### Utilizing Data Preprocessing for Support Vector Machine

#### Import MinMaxScaler

In [21]:
from sklearn.preprocessing import MinMaxScaler

#### Create an Instance of MinMaxScaler as "scaler"

In [22]:
scaler=MinMaxScaler()

#### Fit and transform the X_train and X_test sets to scale and assign the scaled results into variables

In [23]:
scaler.fit(X_train)
scaled_X_train=scaler.transform(X_train)
scaled_X_test=scaler.transform(X_test)

#### Train a new SVC model using the scaled datasets

In [24]:
scaled_svc=SVC()
scaled_svc.fit(scaled_X_train,y_train)

c:\users\service unit\appdata\local\programs\python\python38\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC()

#### Fit the scaled test dataset to the trained model to create a new prediction set

In [25]:
scaled_svc_pred = scaled_svc.predict(scaled_X_test)

#### Compare the new predicted set to the true values in the test dataset using the imported metrics

In [26]:
print(confusion_matrix(y_test, scaled_svc_pred))
print(classification_report(y_test, scaled_svc_pred))

[[43  4]
 [ 0 67]]
              precision    recall  f1-score   support

           0       1.00      0.91      0.96        47
           1       0.94      1.00      0.97        67

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114



Highly significant increase in the overall prediction score is realized after utilizing the Minmax Scaler Preprocessor

## Random Forest

#### Import the Random forest Classifier Algorithm

In [27]:
from sklearn.ensemble import RandomForestClassifier

#### Create an instance of the Random forest model and fit the training data to train

In [28]:
ranfor=RandomForestClassifier()
ranfor.fit(X_train, y_train)

<ipython-input-28-276768d86402>:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  ranfor.fit(X_train, y_train)


RandomForestClassifier()

#### Fit the testing data to the trained model to create a prediction set and assign to variable

In [29]:
ranfor_pred=ranfor.predict(X_test)

#### Compare the prediction set to the true data of the test set

In [30]:
print(confusion_matrix(y_test, ranfor_pred))
print(classification_report(y_test, ranfor_pred))

[[42  5]
 [ 1 66]]
              precision    recall  f1-score   support

           0       0.98      0.89      0.93        47
           1       0.93      0.99      0.96        67

    accuracy                           0.95       114
   macro avg       0.95      0.94      0.94       114
weighted avg       0.95      0.95      0.95       114

